function [ ] = Plot_DD_Delay_by_session(varargin)
%08-15-2010 A.E.P.  This function finds all the .mat within a directory that were generated by the
%program DD#.m  It assumes the variables ZoneIn and ZoneDelay are part of
%the .mat files.  The function generates a plot of the delay versus the lap
%# with the Right side choices (Zone 4) = to blue lines and Left side
%choices (Zone 3) = to red lines.  Each session is one subplot.
%
% |---2---|
% 3   |   4
% |   |   |
% |---1---|
nL=200;
SSN = GetSSN();
process_varargin(varargin);


if iscell(SSN); nXY = max(ceil(sqrt(length(SSN))),5); nS=length(SSN); else nXY = 1; nS=1; end %Determines the number of subplots in the figure based on factorization of the number of sessions
figure; clf;
for iC = 1:nS;
	if iscell(SSN);
		pushdir(SSN{iC});
		sd = DDinit(pwd,'VT1',0,'VT2',0,'Keys',1,'Spikes',0,'DD',1);
		%sd = DDsw_FixSwitchLap(sd);
		cd ..
	else
		sd = DDinit(pwd,'VT1',0,'VT2',0,'Keys',1,'Spikes',0,'DD',1);
		%sd = DDsw_FixSwitchLap(sd);
	end
	subplot(nXY,nXY,iC); hold on; 
	L=1:length(sd.ZoneDelay);
	plot(L(sd.ZoneIn==3), sd.ZoneDelay(sd.ZoneIn==3), 'r.', L(sd.ZoneIn==4), sd.ZoneDelay(sd.ZoneIn==4), 'b.');
	%try line([sd.SwitchLap, sd.SwitchLap],[1 30],'color','k','linewidth',1); catch; end
	axis([0 nL 0 30]);
	%if iscell(SSN); title(SSN{iC}); else title(SSN); end
	%title(mat2str(max(sd.World.nPleft,sd.World.nPright)));
% 	title(strcat(sd.ExpKeys.Condition,'_',mat2str(sd.ExpKeys.PelletRatio)));
    title(mat2str(sd.ExpKeys.PelletRatio));
end
